[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
tungstenite = "0.24.0"
nx = { git = "ssh://git@github.com/ChWeTa/nx.git", version = "0.1.0", branch = "WebSockets" }
